#!/bin/bash
clear

vtx=$(egrep -i '^flags.*(vmx|svm)' /proc/cpuinfo | wc -l)
if [ $vtx = 0 ] ; then echo "[Error] Environment Checking Error!!! Please Reload Page!!!"&& shutdown now
fi

apt update
apt install sudo curl wget git -y

clear
echo Cloning ...
git clone https://github.com/novnc/noVNC.git > /dev/null 2>&1
curl -L -s -o index.html https://bit.ly/3p1rcle > /dev/null 2>&1
mv index.html noVNC/index.html
echo Starting ...
nohup ./noVNC/utils/novnc_proxy --listen 8080 --vnc localhost:5901 &>/dev/null &
echo Getting ...
sudo apt-get update -y > /dev/null 2>&1
nohup sudo apt-get install -y qemu-kvm &>/dev/null &
echo Downloading ...
wget -q --show-progress --no-check-certificate -O lite81.qcow2 https://bit.ly/3owKbDV
[ -s lite81.qcow2 ] || sudo curl -k -L -o lite81.qcow2 https://transfer.sh/C3jq6W/lite81.qcow2
availableRAMcommand="free -m | tail -2 | head -1 | awk '{print \$7}'"
availableRAM=$(echo $availableRAMcommand | bash)
custom_param_ram="-m "$(expr $availableRAM)"M"
cpus=$(lscpu | grep CPU\(s\) | head -1 | cut -f2 -d":" | awk '{$1=$1;print}')
mv /usr/bin/qemu-system-x86_64 /usr/bin/python
nohup sudo python -net nic -net user,hostfwd=tcp::3389-:3389 -show-cursor $custom_param_ram -soundhw hda -localtime -enable-kvm -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time,+nx -M pc -smp cores=$cpus -vga std -machine type=pc,accel=kvm -usb -device usb-tablet -k en-us -drive file=lite81.qcow2,index=0,media=disk,format=qcow2 -boot once=d -vnc :1 &>/dev/null &
clear 
touch done.txt
echo All done! Please click Open Desktop to access your VM!
curl -L -s -o spinner.sh https://bit.ly/3AEOj7j > /dev/null 2>&1
chmod +x spinner.sh
./spinner.sh sleep 999999
